Method
molpro/iMolpro pull request #62
Opened 2023-10-13 07:18 UTC by klauspdoll

this is all very basis, just to start with the method

probably better the methods from molpro_input.py should be read etc etc

name: combo_method ,  or combo_guided_method, or other names ?

2023-10-15 06:38 UTC, pjknowles commented on ProjectWindow.py
> +        self.guided_layout.addWidget(combo_method)
Suggest to instead use `guided_form.addRow('Method',combo_method)`

2023-10-15 06:44 UTC, pjknowles requested changes
It's a good start. You can can continue by connecting a function to `combo_method.currentIndexChanged`.

2023-10-15 06:44 UTC, pjknowles commented on ProjectWindow.py
> +        combo_method.addItem("RHF")
You could instead do `combo_method.addItems(['RHF','MP2','CCSD'])` in preparation for eventually getting the list from the registry.

2023-10-15 06:44 UTC, pjknowles commented on ProjectWindow.py
> +        combo_method = QComboBox()
It's probably best to make this a class variable `self.combo_method` so `refresh_guided_pane` can update it if the raw input gets changed.

2023-10-16 11:54 UTC, pjknowles commented on ProjectWindow.py
> +        self.guided_layout.addWidget(self.combo_method)
I still think that, at least for the moment, it'd be better to add this with `guided_form.addRow()` so that you keep the label with the selector.

It still needs the analogous function to `guided_basis_input_changed()`, and then this connected to changes in `self.combo_method`

2023-10-16 12:05 UTC, pjknowles commented on ProjectWindow.py
> +        self.guided_layout.addWidget(self.combo_method)
It also needs the equivalent of https://github.com/molpro/iMolpro/blob/435834cdd8d176b479729da104aa9dedf871f837/ProjectWindow.py#L292 to set the selected value in `self.combo_method` from the input.

2023-10-16 12:07 UTC, pjknowles commented on ProjectWindow.py
> +        self.combo_method = QComboBox()
Consider naming this `self.guided_combo_method` as it's a property of the guided mode stuff, not the whole `ProjectWindow`. Maybe it's better for us to split out a separate class for all this stuff.

2023-10-16 13:24 UTC, klauspdoll commented
I have included a callback function now, however have commented where something really happens. When I execute the line
`self.refresh_input_from_specification()`
then after changing the pulldown, it says:

Guided mode cannot be used because the input is too complex.

It correctly shows "MP2" in the non-guided input window, but probably cannot make a guided mode out of that.

![guided-mode-mp2](https://github.com/molpro/iMolpro/assets/109160884/0f578e36-cc58-4879-87b3-000a4102498a)

2023-10-16 14:16 UTC, pjknowles commented
> It correctly shows "MP2" in the non-guided input window, but probably cannot make a guided mode out of that.

This is because the check is not sufficiently case-insensitive. I'll fix that now.

For MP2, CCSD and so on, it'll also need `precursor_methods` filling.

2023-10-17 09:22 UTC, pjknowles commented on ProjectWindow.py
> +        combo_method.addItem("RHF")
> You could instead do `combo_method.addItems(['RHF','MP2','CCSD'])` in preparation for eventually getting the list from the registry.

@klauspdoll pymolpro 1.4.1 now contains a function to get data from the registry: https://molpro.github.io/pymolpro/pymolpro.html#pymolpro.project.Project.registry

2023-10-17 11:50 UTC, klauspdoll commented on ProjectWindow.py
> +        combo_method.addItem("RHF")
How can I make use of that?
`from pymolpro import Project`
is already there, but e.g. this (git diff)
`+        print(self.project.registry())`
gives an error 
```
    print(self.project.registry())
          ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Project' object has no attribute 'registry'

```

2023-10-17 11:55 UTC, pjknowles commented on ProjectWindow.py
> +        combo_method.addItem("RHF")
It'll be in conda-forge later today, or you can get the `pymolpro` source and run build.sh in your python environment.

2023-10-17 11:58 UTC, klauspdoll commented on ProjectWindow.py
> +        combo_method.addItem("RHF")
Okay, I'll wait for conda-forge. I noticed that the switch from pulldown to freehand now works, but the other direction not yet fully (when typing mp2, then the pulldown remains at HF - I'll look into that)

2023-10-17 12:00 UTC, pjknowles commented on ProjectWindow.py
> +        combo_method.addItem("RHF")
Of course. There's an earlier comment about that - you need to set this from what is in the input.

2023-10-20 13:53 UTC, pjknowles commented
@klauspdoll I'm conscious that this PR has been open for a week, and we shouldn't just let it go stale. It seems to me that it has reached a point that we understand the remaining next steps, so it could just be merged. OK if I just do that?

2023-10-20 13:56 UTC, klauspdoll commented
Yes, that's excellent. I had similar thoughts, but didn't want to press ahead .....

I have been held up with email etc etc, and hope I'll find time soon

2023-10-20 13:58 UTC, pjknowles approved these changes

2023-10-20 14:01 UTC, merged