begin with wave function symmetry pulldown
molpro/iMolpro pull request #94
Opened 2023-11-08 10:47 UTC by klauspdoll

placement of "Wave Function Characteristics:"

and the corresponding pulldowns such as

'Wave function symmetry'

will have to be fixed later

2023-11-08 10:48 UTC, klauspdoll commented
further commits to follow, do not consider to merge yet

2023-11-08 13:33 UTC, klauspdoll commented
This may now be considered to be merged.

Please note that the symmetry pulldown will have to be extended with the irreps in cases when symmetry can be used. This needs molpro --geometry to be run.

2023-11-09 12:16 UTC, pjknowles reviewed
Just a remark that the way I envisaged this would be done was simply through the molpro variables `symmetry` and `spin`, which maybe reduces the necessary logic (support for variables is already there). However we should consider supporting, either additionally or instead, `wf, symmetry=1, spin=0`. I would suggest sticking with the simplest possible, which is to use the variable syntax as the canonical form, but to support, if we can, parsing the alternate `wf`. But there may be other points of view.

2023-11-09 12:32 UTC, klauspdoll commented
Yes, that's fine with, to keep it as simple as possible. I'll use symmetry,nosym then for the input.

2023-11-09 12:35 UTC, pjknowles commented
Oh, I must have been getting confused. I was thinking about the wavefunction symmetry, rather than the `symmetry` directive, but of course we never had that in gmolpro, and it's difficult to specify anyway, unless you know how the orientation will turn out.

2023-11-09 12:45 UTC, klauspdoll commented
Yes, I made the same mistake.

There is "nosym" in gmolpro to complete disable use of  spatial symmetry, and then the wave function will be irrep 1; or "automatic" to use what Molpro discovers as spatial symmetry.

In the Molpro manual, it is even stated "It is therefore advisable to use the nosym directive as first line in the geometry input. "

For the wave function symmetry, there is wf,symmetry=3 or whatever.

It is a bit confusing because the gmolpro pulldown includes both, to make it as easy as possible for the user. I have now a placeholder for the first irrep as an example, but that may also be removed, to have just "automatic" or "nosym". The irreps need to be discovered first by running molpro --geometry

2023-11-14 09:01 UTC, klauspdoll commented
Peter, can this be merged now?

2023-11-14 09:17 UTC, pjknowles commented on ProjectWindow.py
> +        if self.input_tabs.currentIndex() != 0:
Why is this necessary? I had thought that `input_specification_change()` would be called only as a consequence of interaction on the guided mode pane, and so `self.input_tabs.currentIndex()` should always return 1. But if there is another mode of use, I'd like to understand.

2023-11-14 09:30 UTC, pjknowles commented on molpro_input.py
> +        elif command.lower() == 'nosym':
We need support for `symmetry, nosym` as well. In fact, https://www.molpro.net/manual/doku.php?id=molecular_geometry#symmetry_specification offers that as the normal command, with `nosym` as an alias.

2023-11-14 09:35 UTC, pjknowles requested changes
Looks OK after dealing with whether the test on input pane focus is necessary, and `symmetry,nosym`

2023-11-14 13:47 UTC, klauspdoll commented on ProjectWindow.py
> +        if self.input_tabs.currentIndex() != 0:
I think it slipped in with the merge in a822b073ca . I don't remember exactly, but I think git had not reported a merge conflict, and it went in. I'll remove it.

2023-11-14 13:57 UTC, klauspdoll commented on ProjectWindow.py
> +        if self.input_tabs.currentIndex() != 0:
Oh, and now it seems that it is necessary. When I remove it, and switch from guided to freehand, then I get a funny window (see attachment). Happens for me when I start with a new project, go to freehand mode, and then e.g. add "optg" in the last line, and go to guided mode.


![aftertyping-nosym](https://github.com/molpro/iMolpro/assets/109160884/66d13d18-ddd1-4aa6-a6e2-cb71cd545380)

2023-11-14 14:04 UTC, pjknowles commented on ProjectWindow.py
> +        if self.input_tabs.currentIndex() != 0:
I can't reproduce it. Does the problem go away if you `git revert aa03d6a8` (see https://github.com/molpro/iMolpro/issues/99) ?

2023-11-14 14:10 UTC, pjknowles commented on ProjectWindow.py
> +        if self.input_tabs.currentIndex() != 0:
I have tried to trap the case that `self.input_tabs.currentIndex()` returns zero in `input_specification_change()`, but could not get it to do that. I suspect it arises when called in the thread as set up in aa03d6a8 , and so I simply have to find another way to resolve #99. For now, I will revert aa03d6a8.

2023-11-14 14:11 UTC, klauspdoll commented on ProjectWindow.py
> +        if self.input_tabs.currentIndex() != 0:
I have done the following: master, compare aa03d6a8 and the commit before which is 09ada9e155cb9379fa

```
git checkout master
git checkout  09ada9e155cb9379fa
python iMolpro.py

```
new project, freehand mode, add "optg" in last line, switch to guided mode, OK

```
git checkout aa03d6a8
python iMolpro.py

```
new project, freehand mode, add "optg" in last line, 

error message in terminal:

`QObject::setParent: Cannot set parent, new parent is in a different thread`

switch to guided mode, BUG as displayed above

So I would expect that reverting aa03d6a8 would fix the bug,

2023-11-14 14:27 UTC, klauspdoll commented on ProjectWindow.py
> +        if self.input_tabs.currentIndex() != 0:
After reverting aa03d6a8 with ea3be2307 , the aforementionted problem is gone. I have now done 6ba348a63 so that the initial question has been addressed.

2023-11-14 14:28 UTC, klauspdoll commented on ProjectWindow.py
> +        if self.input_tabs.currentIndex() != 0:
Should be resolved now, I mark it as such.

2023-11-15 11:29 UTC, klauspdoll commented
I have pushed a commit so that

`symmetry,nosym`
`symmetry,  nosym  `
`     symmetry,   nosym`


can now be dealt with. There is however an exception:

`symmetry   ,nosym`

is not recognised. This should probably be dealt with in a general way, i.e. perhaps in `canonicalise` or in the loop over `line` in `parse`.

Would it be correct to delete/ignore all blanks before a comma , or are there exceptions?

2023-11-15 11:39 UTC, pjknowles commented
> can now be dealt with. There is however an exception:
> 
> `symmetry ,nosym`
> 
> is not recognised. This should probably be dealt with in a general way, i.e. perhaps in `canonicalise` or in the loop over `line` in `parse`.
> 
> Would it be correct to delete/ignore all blanks before a comma , or are there exceptions?

Yes. Probably this should be done in `canonicalise()` to support the general strategy that hand-typed inputs do not get rewritten except if really necessary.

2023-11-15 12:54 UTC, klauspdoll commented
Peter, could you please have look if it is okay now?

2023-11-15 14:40 UTC, pjknowles commented on molpro_input.py
> +                                  re.sub(' *, *', ',',
Of course it's fine. It would have taken me 10 seconds instead of 5 minutes to check this if it hadn't been accompanied by the simultaneous manual reformatting!

2023-11-15 14:45 UTC, pjknowles commented on molpro_input.py
> +
Would it perhaps be better to go the other way round, ie `symmetry,nosym` is what will normally get written, but `nosym` will be parsed as equivalent? It is in line with the manual, and perhaps leads to input files that are more easy to understand.

2023-11-15 15:01 UTC, klauspdoll commented on molpro_input.py
> +
This is what it does: when you choose "No symmetry" in the pulldown, then you get

"symmetry,nosym"

2023-11-15 15:10 UTC, pjknowles commented on molpro_input.py
> +
Ah, sorry, I misunderstood, and saw it the other way round for some reason.

2023-11-15 15:29 UTC, pjknowles commented on molpro_input.py
> +
But it is confusing that it works the other way round from `job_type_aliases`.  Line 231 always sets it to the alias, ie `nosym`, not the canonical form. I think it all works correctly, but we might straighten the logic to be more consistent. Let's merge first.

2023-11-15 15:30 UTC, pjknowles approved these changes
It's working.

2023-11-15 15:31 UTC, merged